name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false

    services:
      mysql:
        image: mysql:9.0
        env:
          # MySQL docker container requires these env vars to create the test db
          # See: https://hub.docker.com/_/mysql
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: p@55wOrd
        ports:
          - 3306:3306
          # Before continuing, verify the mysql container is reachable from the ubuntu host
        options: 
          --health-cmd="mysqladmin ping" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3
    env:
      DATABASE_URL: server=localhost;uid=root;pwd=p@55wOrd;database=test

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
      - id: setup-bun
        name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - id: install-deps
        name: Install dependencies
        run: |
          bun install
      - id: test
        name: Run test
        run: |
          bun test
      - id: build
        name: Run build
        run: |
          bun install -g uglify-js shx
          bun run build
